# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease_DrugType_Score',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hypertension.Score')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypertension.Disease')),
                ('drugType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypertension.DrugType')),
            ],
            bases=('hypertension.score',),
        ),
        migrations.CreateModel(
            name='DrugType_DrugType_Score',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hypertension.Score')),
                ('drugTypeA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugTypeA', to='hypertension.DrugType')),
                ('drugTypeB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugTypeB', to='hypertension.DrugType')),
            ],
            bases=('hypertension.score',),
        ),
        migrations.CreateModel(
            name='SideEffect_DrugType_Score',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hypertension.Score')),
                ('drugType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypertension.DrugType')),
                ('sideEffect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypertension.SideEffect')),
            ],
            bases=('hypertension.score',),
        ),
    ]
